# Default values for con-lo-ojo-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: con-lo-ojo-bot
  version: latest
  pullPolicy: IfNotPresent

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 1Gi
  # requests:
  #   cpu: 200m
  #   memory: 1Gi
