apiVersion: apps/v1
kind: Deployment
metadata:
  name: con-lo-ojo-bot
  labels:
    app: con-lo-ojo-bot
    name: bot-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: con-lo-ojo-bot
      name: bot-deployment
  template:
    metadata:
      labels:
        app: con-lo-ojo-bot
        name: bot-deployment
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-token-secret
                  key: token
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
