apiVersion: v1
kind: Service
metadata:
  name: bot-service
  labels:
    app: con-lo-ojo-bot
    name: bot-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: con-lo-ojo-bot
    name: bot-deployment
